{{-  $t2vNvidia := and (index .Values "modules" "text2vec-nvidia" "enabled") (index .Values "modules" "text2vec-nvidia" "apiKey") -}}
{{-  $generativeNvidia := and (index .Values "modules" "generative-nvidia" "enabled") (index .Values "modules" "generative-nvidia" "apiKey") }}
{{-  $rerankerNvidia := and (index .Values "modules" "reranker-nvidia" "enabled") (index .Values "modules" "reranker-nvidia" "apiKey") }}
{{-  $multi2vecNvidia := and (index .Values "modules" "multi2vec-nvidia" "enabled") (index .Values "modules" "multi2vec-nvidia" "apiKey") }}
{{-  $nvidia := or ($t2vNvidia) ($generativeNvidia) ($rerankerNvidia) ($multi2vecNvidia) }}
{{- if $nvidia }}

{{- $apiKeys := list }}
{{- if $t2vNvidia }}
  {{- $apiKeys = append $apiKeys (index .Values "modules" "text2vec-nvidia" "apiKey") -}}
{{- end }}
{{- if $generativeNvidia }}
  {{- $apiKeys = append $apiKeys (index .Values "modules" "generative-nvidia" "apiKey") -}}
{{- end }}
{{- if $rerankerNvidia }}
  {{- $apiKeys = append $apiKeys (index .Values "modules" "reranker-nvidia" "apiKey") -}}
{{- end }}
{{- if $multi2vecNvidia }}
  {{- $apiKeys = append $apiKeys (index .Values "modules" "multi2vec-nvidia" "apiKey") -}}
{{- end }}

{{- if gt (len ($apiKeys | uniq)) 1 -}}
  {{- fail "nvidia modules activated, but their keys differ. Use the same key on all activated nvidia modules." }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  {{- if .Values.namespaceOverride }}
  namespace: {{ .Values.namespaceOverride }}
  {{- end }}
  name: weaviate-nvidia
  labels:
    app.kubernetes.io/name: weaviate
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{- if (index .Values "modules" "generative-nvidia" "apiKey") }}
  apiKey: {{ index .Values "modules" "generative-nvidia" "apiKey" | b64enc }}
  {{- else if (index .Values "modules" "reranker-nvidia" "apiKey") }}
  apiKey: {{ index .Values "modules" "reranker-nvidia" "apiKey" | b64enc }}
  {{- else if (index .Values "modules" "multi2vec-nvidia" "apiKey") }}
  apiKey: {{ index .Values "modules" "multi2vec-nvidia" "apiKey" | b64enc }}
  {{- else }}
  apiKey: {{ index .Values "modules" "text2vec-nvidia" "apiKey" | b64enc }}
  {{- end }}
{{ end }}
