{{ if and (index .Values "modules" "text2vec-morph" "enabled") (index .Values "modules" "text2vec-morph" "apiKey") }}
apiVersion: v1
kind: Secret
metadata:
  {{- if .Values.namespaceOverride }}
  namespace: {{ .Values.namespaceOverride }}
  {{- end }}
  name: weaviate-morph
  labels:
    app.kubernetes.io/name: weaviate
    app.kubernetes.io/managed-by: helm
type: Opaque
data:
  apiKey: {{ index .Values "modules" "text2vec-morph" "apiKey" | b64enc }}
{{ end }}
