{{ if and (index .Values "modules" "generative-xai" "enabled") (index .Values "modules" "generative-xai" "apiKey") }}
apiVersion: v1
kind: Secret
metadata:
  {{ if .Values.namespaceOverride }}
  namespace: {{ .Values.namespaceOverride }}
  {{ end }}
  name: weaviate-xai
  labels:
    app.kubernetes.io/name: weaviate
    app.kubernetes.io/managed-by: helm
type: Opaque
data:
  apiKey: {{ index .Values "modules" "generative-xai" "apiKey" | b64enc }}
{{ end }}
