{{ if and (index .Values "modules" "generative-anthropic" "enabled") (index .Values "modules" "generative-anthropic" "apiKey") }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ default .Release.Namespace .Values.namespaceOverride }}
  name: weaviate-anthropic
  labels:
    app.kubernetes.io/name: weaviate
    app.kubernetes.io/managed-by: helm
type: Opaque
data:
  apiKey: {{ index .Values "modules" "generative-anthropic" "apiKey" | b64enc }}
{{ end }}
