{{- $podDisruptionBudget := index .Values "podDisruptionBudgets" "text2vec-gpt4all" -}}
{{- $module := index .Values "modules" "text2vec-gpt4all" -}}
{{- if and (index $podDisruptionBudget "enabled") (index $module "enabled") }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  {{- if .Values.namespaceOverride }}
  namespace: {{ .Values.namespaceOverride }}
  {{- end }}
  name: {{ index $module "fullnameOverride" }}
  labels:
    name: {{ index $module "fullnameOverride" }}
    app: {{ index $module "fullnameOverride" }}
    app.kubernetes.io/name: weaviate
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ index $module "fullnameOverride" }}
  {{- toYaml $podDisruptionBudget.spec | nindent 2 }}
{{- end -}}
