{{ if and (index .Values "modules" "generative-friendliai" "enabled") (index .Values "modules" "generative-friendliai" "token") }}
apiVersion: v1
kind: Secret
metadata:
  {{- if .Values.namespaceOverride }}
  namespace: {{ .Values.namespaceOverride }}
  {{- end }}
  name: weaviate-friendliai
  labels:
    app.kubernetes.io/name: weaviate
    app.kubernetes.io/managed-by: helm
type: Opaque
data:
  token: {{ index .Values "modules" "generative-friendliai" "token" | b64enc }}
{{ end }}
